//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission_Item
    {
        public int PermissionId { get; set; }
        public int ItemCode { get; set; }
        public int Quantity { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
